[package]
name = "hand-parser"
version = "0.1.0"
authors = ["Jonathan Neufeld <jneufeld@alumni.ubc.ca>"]
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"